### ISSUE TITLE
P0 turns into P1 after using uBit.audio.setPin(uBit.io.P1)

### ISSUE THREAD

**Issue by dpgeorge** [lancaster-university/codal-microbit-v2#115]
See https://github.com/microbit-foundation/micropython-microbit-v2/issues/69#issuecomment-855948709

Reproduction in C++ using CODAL v0.2.28:
```c
#include "MicroBit.h"

MicroBit uBit;

int main() {
    uBit.init();

    uBit.serial.printf("== start ==\r\n");
    uBit.serial.printf("P0.name=%d\r\n", uBit.io.P0.name);
    uBit.serial.printf("P1.name=%d\r\n", uBit.io.P1.name);
    uBit.serial.printf("P2.name=%d\r\n", uBit.io.P2.name);

    uBit.audio.setPin(uBit.io.P1);

    uBit.serial.printf("== end ==\r\n");
    uBit.serial.printf("P0.name=%d\r\n", uBit.io.P0.name);
    uBit.serial.printf("P1.name=%d\r\n", uBit.io.P1.name);
    uBit.serial.printf("P2.name=%d\r\n", uBit.io.P2.name);

    for(;;);
}
```
Output:
```
== start ==
P0.name=2
P1.name=3
P2.name=4
== end ==
P0.name=3
P1.name=3
P2.name=4
```
From then on, P0 behaves like P1 because its `.name` field has been overwritten with "3".

**Comment by martinwork** [comment]
Thanks @dpgeorge . I can see why: MicroBitAudio::pin is a NRF52Pin & reference.

@finneyj Should I simply change the internal MicroBitAudio::pin to a pointer?

**Comment by finneyj** [comment]
Yes please @martinwork - absolutely the thing to do.

Apologies @dpgeorge.

**Comment by martinwork** [comment]
Created PR https://github.com/lancaster-university/codal-microbit-v2/pull/116.

**Comment by dpgeorge** [comment]
Thanks for the quick turn around!  Can confirm the bug is fixed.

**Comment by martinwork** [comment]
Thanks for confirming @dpgeorge
