### ISSUE TITLE
uart send receive

### ISSUE THREAD

**Issue by tcpipchip** [lancaster-university/codal-microbit-v2#117]
Sir,

Is there a sample that show how to send and receive data from UART using POLLING ?

Can you help us ?

Thank you!

**Comment by microbit-carlos** [comment]
Hi @tcpipchip,

Apologies for the long delay on a reply.

You can use the `SYNC_SPINWAIT` mode when using the `uBit.serial.send()` or `uBit.serial.read()` and that will block until data is in/out. There is a bit more info on how that works here: https://lancaster-university.github.io/microbit-docs/ubit/serial/

As it's an old issue I'll close this as resolved, as hopefully the info above answered your question! But if it hasn't or you have any other questions related to this please do reopen the issue and we can look into it 👍 

Thanks!
