### ISSUE TITLE
serial.send ASYNC sends a partial string if it's larger than the buffer 

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#149]
Using the ASYNC mode in serial.send() fills the buffer but anything that doesn't fit is not send. So a program like this:

- [MICROBIT.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/7424710/MICROBIT.hex.zip)
```cpp
#include "MicroBit.h"

MicroBit uBit;

int main() {
    uBit.init();
    while (true) {
        uBit.serial.send(
            "This should be a very long string so that it takes several buffer fills before the string is fully sent via UART\n",
            ASYNC
        );
        uBit.sleep(5000);
    }
}
```

Constantly sends the first 40 characters `This should be a verThis should be a ver` continuously and ignores the rest of the string.

```
This should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a verThis should be a ver
```

I believe this is the same case in the v1 DAL, but it is unintuitive why the full string is not sent and I would consider this a bug in both HALs.

**Comment by JohnVidler** [comment]
Merged and fixed in the upstream

**Comment by martinwork** [comment]
@JohnVidler @microbit-carlos
ASYNC mode is meant to fill the buffer and return the number of bytes copied. The caller can then decide what to do.

This new behaviour seems very much like SYNC_SLEEP, except it will block for a number of milliseconds, rather than on the buffer empty event.

I imagine this could be a breaking change for some code.
The documentation could be clearer.

https://lancaster-university.github.io/microbit-docs/ubit/serial/
ASYNC - bytes are copied into the txBuff and returns immediately.
SYNC_SLEEP - bytes are copied into the txBuff and the fiber sleeps until all bytes have been sent. This allows other fibers to continue execution.
Returns
the number of bytes written

**Comment by microbit-carlos** [comment]
@JohnVidler reopening to see if we need to reconsider this for the next maintenance release.

**Comment by JohnVidler** [comment]
Based on our conversation in person @finneyj do we conder this a regression and we should go back to the original behaviour described here, rather than patching to a different behavior (like my patch that deschedules the fiber)

**Comment by JohnVidler** [comment]
Ok, so suggested altered beheviour for ASYNC mode would be to attempt to just drop the data off in the serial buffer, then if we run out of space, bail immediately and return the number of bytes actually sent. via:

```
if(mode == ASYNC)
                return copiedBytes; // Explicitly return less than the full string. We can't 'immediately return' if we have to wait for more buffer space.
                                    // Note that for applications that need to guarantee this works every time, they should set the buffer length before calling send().
```

Such that if applications _absolutely need_ to send giant strings in ASYNC mode, they're required to set the transmit buffer up beforehand with enough space to deal with their longest strings, as per:

```
        uBit.serial.setTxBufferSize( 32 );
        int sentBytes = uBit.serial.send(
            "This should be a very long string so that it takes several buffer fills before the string is fully sent via UART\n",
            ASYNC
        );
        uBit.sleep( 500 );
        uBit.serial.printf( "Sent %d bytes!\n", sentBytes );
        uBit.sleep(1000);

        uBit.serial.setTxBufferSize( 255 );
        sentBytes = uBit.serial.send(
            "This should be a very long string so that it takes several buffer fills before the string is fully sent via UART\n",
            ASYNC
        );
        uBit.sleep( 500 );
        uBit.serial.printf( "Sent %d bytes!\n", sentBytes );
        uBit.sleep(1000);
```

Which results in this in the serial terminal:
```
This should be a very long strinSent 32 bytes!
This should be a very long string so that it takes several buffer fills before the string is fully sent via UART
Sent 113 bytes!
This should be a very long strinSent 32 bytes!
This should be a very long string so that it takes several buffer fills before the string is fully sent via UART
Sent 113 bytes!
```

This way applications can check if their transmitted data matches what they expect if this is critical (or use the other send modes) and still just have high-speed throwaway serial messages via ASYNC provided that there is sufficient buffer space to handle this. (Note that the max. buffer length is 255)

Obviously this would need to be updated in the docs to reflect the subtleties.

I think this is a reasonable compromise to match the API spec in the docs _and_ handle overflow sensibly.

Thoughts @martinwork , @microbit-carlos , @finneyj  ?

**Comment by JohnVidler** [comment]
Ah, just re-read your comments above @martinwork - so yes, agreed on...

> ASYNC mode is meant to fill the buffer and return the number of bytes copied. The caller can then decide what to do.

...plus some documentation updates.

**Comment by JohnVidler** [comment]
I've created a PR over in the `codal-core` repo with my proposed fix for this behaviour: https://github.com/lancaster-university/codal-core/pull/148

**Comment by martinwork** [comment]
@JohnVidler

Before the commit that changed it, we had
https://github.com/lancaster-university/codal-core/blob/db201e94c6a2767e881ba4457c4087eb34312603/source/driver-models/Serial.cpp#L99
This breaks from the while loop and calls enableInterrupt(TxInterrupt) before returning.

In the new PR, it returns without calling enableInterrupt(TxInterrupt)
https://github.com/lancaster-university/codal-core/blob/25535d53ce3a231ca579833c6eea44f7ffde3cbe/source/driver-models/Serial.cpp#L99

I think the old version was right.

I use ASYNC mode usually with a large secondary FIFO buffer, which may be getting filled inside an interrupt. After checking how much space there is in the serial buffer, up to that many bytes are transferred from the secondary buffer, without wanting to wait until all those bytes are on their way.

**Comment by JohnVidler** [comment]
Mm, agreed, although I'll keep the documentation updates as they make the usage clearer: See https://github.com/lancaster-university/codal-core/pull/148#issuecomment-1198226292 for the PR comment about this.

I'll update the PR and we can go/no-go on it.

**Comment by JohnVidler** [comment]
Update the PR as described and reverted back to the `break`ing behaviour to preserve the tx interrupt - does this address the issue you had now @martinwork ?

**Comment by martinwork** [comment]
Yes. Thanks @JohnVidler.

**Comment by JohnVidler** [comment]
Merged in core, closing this issue
