### ISSUE TITLE
Busy flag is not implemented in MicroBitPowerManager.cpp

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#165]
As done for `MicroBitUSBFlashManager.h` in the `daplink-interface-versioning`:
- https://github.com/lancaster-university/codal-microbit-v2/compare/daplink-interface-versioning
- https://github.com/lancaster-university/codal-microbit-v2/tree/daplink-interface-versioning

Is not needed as much normally, but if MakeCode is WebUSB connected to the micro:bit we end up with the "waiting for the DAPLink to respond" function (`MicroBitPowerManager::awaitUIPMPacket()`) timing out and then the data ends up in `MicroBitPowerManager::idleCallback()` and we get the `UIPM: RECEIVED UNKNWON FRAME` debug message.

**Comment by microbit-carlos** [comment]
In my tests this was actually a bigger issue than the busy flag not being checked: https://github.com/lancaster-university/codal-microbit-v2/pull/166

Still, the busy flag value should be checked `MicroBitPowerManager::awaitUIPMPacket()`.

**Comment by JohnVidler** [comment]
Created a PR for this ( https://github.com/lancaster-university/codal-microbit-v2/pull/190 ) but I don't have the hadware to test this directly right now. Assuming it works, we can close this and merge the PR.

**Comment by JohnVidler** [comment]
Now merged into main, so closing this issue.
