### ISSUE TITLE
Sound emoji logarithmic interpolation does not pass end frequency

### ISSUE THREAD

**Issue by riknoll** [lancaster-university/codal-microbit-v2#181]
The sound expression code is not passing the end frequency for logarithmic interpolation like it does with the other interpolation functions:

https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/SoundExpressions.cpp#L226

However, the implementation is expecting it:

https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/SoundSynthesizerEffects.cpp#L102

As a result sounds that use logarithmic interpolation either play as clicks or don't play at all.

**Comment by riknoll** [comment]
@finneyj FYI

**Comment by JohnVidler** [comment]
May be related to https://github.com/microsoft/pxt-microbit/issues/4720 - possibly not dealing with never reaching the end frequency?

**Comment by JohnVidler** [comment]
Added an end frequency parameter as per the other interpolation options, see https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/SoundExpressions.cpp#L228

**Comment by JohnVidler** [comment]
See https://github.com/microsoft/pxt-microbit/issues/4720#issuecomment-1150483219 for more details, but I'm going to call this done for now.
