### ISSUE TITLE
Remove unused motion sensor driver

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#184]
the FXOS driver is not used, so we can remove it and the auto-detection with the heap allocation can be removed as well.

**Comment by microbit-carlos** [comment]
@JohnVidler The autodetect functions can be found in this repo:
- https://github.com/lancaster-university/codal-microbit-v2/blob/v0.2.38/source/MicroBitAccelerometer.cpp#L54
- https://github.com/lancaster-university/codal-microbit-v2/blob/v0.2.38/source/MicroBitCompass.cpp#L56

And the drivers itself is in the codal-core repo:
- https://github.com/lancaster-university/codal-core/blob/master/source/drivers/FXOS8700.cpp

**Comment by JohnVidler** [comment]
@microbit-carlos Just checking that these are all OK to just outright remove, and that they have no dependencies?

Would it be prudent to include stubs with `__attribute__ ((deprecated))` tagged on to indicate why this will not work going forwards?

**Comment by JohnVidler** [comment]
So, I've had time to look at this now, and do we still need to have a fallback software Accelerometer class to handle cases where the LSM303 fails? if so, this boils down to simply removing this block of code ( https://github.com/lancaster-university/codal-microbit-v2/blob/v0.2.38/source/MicroBitAccelerometer.cpp#L77 ):

```
        // All known accelerometer/magnetometer peripherals have the same alignment
        if (FXOS8700::isDetected(i2c, 0x3E))
        {
            FXOS8700 *fxos = new FXOS8700(i2c, irq1, coordinateSpaceFXOS8700, 0x3E);
            MicroBitAccelerometer::detectedAccelerometer = fxos;
            MicroBitCompass::detectedCompass = fxos;
        }
```

With no further changes needed. Essentially we then just probe for an LM303, if one responds, use it, else fall back to the software one to prevent hard crashes and/or lockups in cases where it may have failed.

Thoughts?

**Comment by JohnVidler** [comment]
Ok, so I've done more than the above, and greatly minimised the interface internals, removed the old driver, and added in some failure cases for if we can't configure the accelerometer and/or compass on startup.

Ultimately this will be squashed down further for `v0.2.40` or future releases, but this is acceptably squashed for now.
