### ISSUE TITLE
`uBit.audio.soundExpressions.play()` (blocking version) continues to output sound after the function returns

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#189]
With this programme (there is more than the screenshot), which toggles a pin high while the `[play sound until done]` block is running: [microbit-lonely-duckling-debug.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/8855622/microbit-lonely-duckling-debug.hex.zip)

<img width="636" alt="image" src="https://user-images.githubusercontent.com/29712657/172454660-adc3ae01-29c0-4a9d-81d7-db4e6c8843c9.png">

We can see the sound output is actually delayed:

![Screenshot2022_06_01_151858](https://user-images.githubusercontent.com/29712657/172454238-25cdd505-db16-45af-8ced-d90393c3daa3.jpg)

That `[play sound]` block in MakeCode it ultimately ends executing `uBit.audio.soundExpressions.play()` in: 
- https://github.com/microsoft/pxt-microbit/blob/d80514bda223f729d452c1e51047f3272a2317fb/libs/core/soundexpressions.cpp#L11

**Comment by JohnVidler** [comment]
Proposed fix is in PR #210 and if approved will auto-close this issue as solved.

**Comment by microbit-carlos** [comment]
Reopening as this might need further work: https://github.com/lancaster-university/codal-microbit-v2/pull/210#discussion_r948913835

**Comment by microbit-carlos** [comment]
The original patch has also been reverted in v0.2.42-hotfix.1: https://github.com/lancaster-university/codal-microbit-v2/commit/e8e42b2ad8c0218b17ea2cbb9ef147ff94afa062
And in master:  https://github.com/lancaster-university/codal-microbit-v2/commit/696db50150fcde7f97e41fc41efe5159f19c68a7

**Comment by finneyj** [comment]
Resolved, as discussed in: https://github.com/lancaster-university/codal-microbit-v2/issues/231
