### ISSUE TITLE
Statically allocate motion sensor driver

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#194]
Some work has been carried out already in this area for the v0.2.39 release, but it we can go a bit further by fully statically allocate the driver in the stack.

**Comment by JohnVidler** [comment]
Bumped to 0.2.42, but the new driver as update for 0.2.41 is much more friendly to being made static, so considering this 'in progress'.

**Comment by JohnVidler** [comment]
Handling this as a static variable means that other tracking (than just checking if the driver is non-NULL) would need to be added throughout to prevent other components from crashing. So leaving this as it is for now.
