### ISSUE TITLE
MakeCode power extension wakes up and incorrectly turns ON mic LED

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#200]
## Description

Basically pressing button A will put the board to sleep for 1 second, and the first time it wakes up it always turns on the microphone LED. 
Subsequent sleeps wake up and turn off the LED, and it does't trigger anymore until the reset button is pressed.

## Test Programme

<img width="661" alt="image" src="https://user-images.githubusercontent.com/29712657/176004273-d54dea26-021b-419e-b0a7-578886b73e16.png">

```ts
input.onButtonPressed(Button.A, function () {
    basic.showString("A")
    power.lowPowerPause(1000)
})
basic.forever(function () {
    basic.showIcon(IconNames.Heart)
    basic.showIcon(IconNames.SmallHeart)
})
```

## Hardware & Software

Tested on a V2.2 using the micro:bit power management extension and MakeCode live.

MakeCode info:
- makecode.microbit.org version:  [5.0.6](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.0.6)
- Microsoft MakeCode version:  [8.0.3](https://github.com/Microsoft/pxt/releases/tag/v8.0.3)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.40](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.40)

Extension is hosted here: https://github.com/microbit-foundation/pxt-microbit-v2-power
In my case I loaded the version shown in the MakeCode extensions gallery when searching for "power", which is the latest release:
```json
{
    "name": "Pwr test",
    "description": "",
    "dependencies": {
        "core": "*",
        "radio": "*",
        "microphone": "*",
        "power": "github:microbit-foundation/pxt-microbit-v2-power#v0.2.3"
    },
    "files": [
        "main.blocks",
        "main.ts",
        "README.md"
    ],
    "targetVersions": {
        "branch": "v1.2.13",
        "tag": "v1.2.13",
        "commits": "https://github.com/Microsoft/pxt-microbit/commits/5d5b348757b15c6d00f5b7f560fd69592ca29424",
        "target": "1.2.13",
        "pxt": "4.4.7"
    },
    "preferredEditor": "tsprj"
}
```

Share link and hex:
- https://makecode.microbit.org/_cv4VPVLk187p
- [microbit-Pwr-test.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/8994546/microbit-Pwr-test.hex.zip)

**Comment by JohnVidler** [comment]
Placing this in the v0.2.41 release for now, mainly to facilitate tracking it

**Comment by martinwork** [comment]
Programs built by https://makecode.microbit.org/v4 don't seem turn the mic LED on (or off - see https://github.com/microbit-foundation/pxt-microbit-v2-power/issues/8). I don't know if the change is in MakeCode or CODAL. See https://makecode.microbit.org/_ifsMvPRmj6PT (shared from V4, so it should import to either).
![image](https://user-images.githubusercontent.com/989126/184499335-97c0f1f0-562d-4ea4-9a72-ffbd190ac1cc.png)

**Comment by JohnVidler** [comment]
Now should be fixes as of https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.43 so closing this, but feel free to reopen if this reoccurs
