### ISSUE TITLE
MakeCode power extension sleeps w/ mic LED ON, then mic stops working 

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#202]
## Description

This programme using the microphone goes to sleep, but it leaves the microphone LED ON.
Then it wakes up and all is fine.
The next time it goes to sleep, it turns off the microphone LED when it wakes up.
At this point the microphone doesn't seem to work anymore and the LED is OFF.

Likely related to https://github.com/lancaster-university/codal-microbit-v2/issues/200, but this is specifically about the microphone behaviour on a programme that is using it.

## Test Programme

<img width="668" alt="image" src="https://user-images.githubusercontent.com/29712657/176008014-07756383-7a91-4da9-aaf5-84ee70fde882.png">

```ts
input.onButtonPressed(Button.A, function () {
    basic.showString("A")
    power.lowPowerPause(10000)
})
basic.forever(function () {
    basic.showNumber(input.soundLevel())
    basic.showIcon(IconNames.Heart)
})
```

## Hardware & Software

Tested on a V2.2 using the micro:bit power management extension and MakeCode live.

MakeCode info:
- makecode.microbit.org version:  [5.0.6](https://github.com/Microsoft/pxt-microbit/releases/tag/v5.0.6)
- Microsoft MakeCode version:  [8.0.3](https://github.com/Microsoft/pxt/releases/tag/v8.0.3)
- microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
- codal-microbit-v2 runtime version:  [v0.2.40](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.40)

Extension:
- https://github.com/microbit-foundation/pxt-microbit-v2-power
- v0.2.3

Share link and hex:
- https://makecode.microbit.org/_9oiRK60aqiPa
- [microbit-Pwr-test-mic-led.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/8994642/microbit-Pwr-test-mic-led.hex.zip)

**Comment by JohnVidler** [comment]
Placing this in the v0.2.41 release for now, mainly to facilitate tracking it

**Comment by martinwork** [comment]
Programs built by https://makecode.microbit.org/v4 don't seem to have this problem.
See https://makecode.microbit.org/_fu0CM6XJabwc (shared from V4 so it should import into either version). Is the mic working after low power related to whether the mic LED goes off during low power mode?
![image](https://user-images.githubusercontent.com/989126/184500017-d59f172f-9d5e-40fe-9651-835667c10143.png)

**Comment by JohnVidler** [comment]
Finally tracked this down to a bad device ID via MicroBitCompat that was effectively sending spurious control messages, now should be fixed with https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.43 so closing, but do reopen if this reoccurs.

**Comment by martinwork** [comment]
@JohnVidler Related (feel free to close!): https://github.com/lancaster-university/codal-microbit-v2/issues/96
