### ISSUE TITLE
HOW CAN I USE THIS LIB?

### ISSUE THREAD

**Issue by hnwangkg-ezio** [lancaster-university/codal-microbit-v2#207]
Is there any documentation out there about configuring this library?

**Comment by martinwork** [comment]
Hi @hnwangkg-ezio, please see https://github.com/lancaster-university/microbit-v2-samples, where there are installation instructions. The build system there downloads this library and others.

**Comment by microbit-carlos** [comment]
Hopefully you've found the information you needed in https://github.com/lancaster-university/microbit-v2-samples. I'll close this as resolved, but feel free to reopen if you still have any questions.
