### ISSUE TITLE
Method to change I2C and SPI pins

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#226]
MicroPython for V1 offers the option to change the I2C and SPI pins. For V2 this is not currently possible for I2C, and for SPI it needs to destroy and recreate an SPI object.

For I2C this was possible in the DAL, by accessing a protected variables from the Mbed I2C class:
- https://github.com/lancaster-university/microbit-dal/blob/602153e9199c28c08fd2561ce7b43bf64e9e7394/inc/drivers/MicroBitI2C.h#L46
- https://github.com/lancaster-university/mbed-classic/blob/master/api/I2C.h#L167
- https://github.com/bbcmicrobit/micropython/blob/master/inc/microbit/microbitdal.h#L38

And for SPI it could call the lower level SPI HAL functions from Mbed:
- https://github.com/bbcmicrobit/micropython/blob/master/source/microbit/microbitspi.cpp#L85 
- https://github.com/lancaster-university/mbed-classic/blob/427f56863c9f9a9132a213ec583469dfc61c6244/hal/spi_api.h#L68

Can we update CODAL to offer this feature directly via I2C/SPI class methods?

**Comment by finneyj** [comment]
Addressed in:

https://github.com/lancaster-university/codal-core/pull/155
https://github.com/lancaster-university/codal-nrf52/pull/42

**Comment by finneyj** [comment]
Relevant methods here:

https://github.com/lancaster-university/codal-nrf52/blob/dynamic-pin-peripherals/inc/NRF52I2C.h#L70
https://github.com/lancaster-university/codal-nrf52/blob/dynamic-pin-peripherals/inc/NRF52SPI.h#L131

I assume this covers off what you need @microbit-carlos @dpgeorge ?

**Comment by JohnVidler** [comment]
Bumping again, as 44 is likely to be any fixes for MicroPython, and this lot may introduce issues.

**Comment by microbit-carlos** [comment]
PRs were merged in December, so assuming this was released in v0.2.45 (January) instead of v0.2.44 (November).
This is now ready for implementing in MicroPython 🎉
