### ISSUE TITLE
neopixels WS2812B PWM source reads one byte beyond the end of the data

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#241]
In https://github.com/lancaster-university/codal-nrf52/blob/master/source/WS2812B.cpp#L97
The second comparison should be >=.

samplesToSend = length * 8, where length is the number of bytes pointed to by data.

When samplesSent == WS2812B_ZERO_PADDING + samplesToSend,
index = (WS2812B_ZERO_PADDING + samplesToSend - WS2812B_ZERO_PADDING) / 8 = samplesToSend / 8 = length,
and data[ length] is outside the array.

https://github.com/lancaster-university/codal-nrf52/blob/master/source/WS2812B.cpp#L172
```
    this->samplesToSend = length * 8;
    this->samplesSent = 0;

```
https://github.com/lancaster-university/codal-nrf52/blob/master/source/WS2812B.cpp#L97
```
        if (samplesSent < WS2812B_ZERO_PADDING || samplesSent > (WS2812B_ZERO_PADDING + samplesToSend))
        {
            *out = WS2812B_PAD;
        }
        else
        {
            int index = (samplesSent - WS2812B_ZERO_PADDING) / 8;
            int bit = (samplesSent - WS2812B_ZERO_PADDING) % 8;

            *out = ((data[index] >> (7-bit)) & 1) ? WS2812B_HIGH : WS2812B_LOW;
        }
```

**Comment by microbit-carlos** [comment]
@finneyj to take a look.

**Comment by finneyj** [comment]
Thanks @microbit-carlos  @martinwork.

I think you're right that it might be an off by one condition there. The memory write is guarded by the outer loop though: https://github.com/lancaster-university/codal-nrf52/blob/master/source/WS2812B.cpp#L91, which guarantees the write operations are always within the range of the associated ManagedBuffer. 

As the code is safe, and we haven't had any report of any bugs around the code, I'd propose no change.

**Comment by martinwork** [comment]
Sorry, I should have thought in the first place to add some trace to confirm what happens. Reading the next byte after the data changes just the first post data padding value to a high or low. Maybe this doesn't actually matter to the WS2812B, given the amount of padding!

Here's an attempt to write (0,0,0) to a single pixel, with a 255 added after the 3 data bytes. The buffer values are masked with &= ~0x8000.

With >
```
length 3 samplesToSend 24
data 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 255
buffer 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 10 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

data
buffer 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

With >=
```
length 3 samplesToSend 24
data 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
buffer 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0

data
buffer 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
```

[neopixels-buffer.zip](https://github.com/lancaster-university/codal-microbit-v2/files/10472352/neopixels-buffer.zip)
