### ISSUE TITLE
Bluetooth IO Pin Service not allowing control of pin connected devices

### ISSUE THREAD

**Issue by bluetooth-mdw** [lancaster-university/codal-microbit-v2#27]
The Pin Data characteristic belonging to the IO Pin Service allows the state of micro:bit pins to be changed, by writing to the characteristic value. How the data is interpreted depends on the value of other configuration characteristics in the same service. In the simplest case, Pin Data acts as a series of binary pin number/value pairs. 

Writing a value of 0x000101000200 to this characteristic should switch pin 0 on, pin 1 off and pin 2 off. Doing this using the nRF Connect application against a V1 micro:bit, with an LED connected to pin 0, works as expected. The LED switches on. Performing the same test on a micro:bit V2 does not work.

Use this code for testing: https://github.com/bittysoftware/bitty_controller_device_code/blob/master/microbit/makecode/switches.js 

FYI @microbit-mark

**Comment by microbit-mark** [comment]
@martinwork is this fixed by https://github.com/microbit-foundation/codal-microbit/pull/132 and if so should we port this from the private to public repo?

**Comment by martinwork** [comment]
@microbit-mark I think that PR should fix it. The order of the pins in uBit.io changed. I'll make another PR over there, if that's appropriate.

**Comment by finneyj** [comment]
Hi @martinwork  @bluetooth-mdw 

I thought we already reordered the pins to accommodate:
https://github.com/lancaster-university/microbit-dal/blob/master/inc/drivers/MicroBitIO.h
https://github.com/lancaster-university/codal-microbit-v2/blob/master/model/MicroBitIO.h

All the edge connector pins seem to be in the same order?

p.s. Really nice to hear from you again @bluetooth-mdw! Been a long time!

**Comment by martinwork** [comment]
@finneyj You are right, but I think I wrote this before they were reordered:
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/bluetooth/MicroBitIOPinService.cpp#L88

To be honest, I don't see how that would have worked then! It looks like I might have not finished it, and created the issue about changing the order instead!

**Comment by finneyj** [comment]
Indeed, maybe the issue was a blocker and then finishing it just fell off the plate with everything else going on?

Do you fancy taking a look @martinwork ?

**Comment by bluetooth-mdw** [comment]
Hello yourself @finneyj or should I say Professor? :-)

We should catch up!

**Comment by finneyj** [comment]
haha - so you spotted that did you?  You always were a sharp one @bluetooth-mdw. ;)   

Yep, catch up sometime soon would be good!

**Comment by martinwork** [comment]
@bluetooth-mdw This is fixed in v0.2.23. Tested with a hex from MakeCode beta and the micro:bit iOS app.

**Comment by martinwork** [comment]
@bluetooth-mdw Please close if this is OK now.

**Comment by bluetooth-mdw** [comment]
@martinwork Sorry,  I don't have time to test but I'll close all the same.
