### ISSUE TITLE
LevelDetectorSPL::setHighThreshold has no effect

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#273]
Here's a MakeCode (live, CODAL 0.2.40) example showing that setting the threshold high or low has no effect.
It uses the MakeCode console, to record on loud triggers (high), the sound level, and the loud threshold (loud).
https://makecode.microbit.org/_Ma29EU70DKKX
The MakeCode level never goes above 131, which maps to CODAL level 87. MakeCode clips the CODAL value to [52,120] and maps that range to [0,255].
The sample starts with threshold = 255 (~CODAL 120), but loud claps still trigger on loud.
Press A to set the threshold to 40. Then it's possible to record levels well above 40 without triggering on loud, but still possible to trigger with a clap.
Press B to set the threshold to 150 and see results like 255, just to confirm that 255 isn't a special case.

Here's C++, with hex built with 0.2.40, with matching MakeCode console output. It uses CODAL level 120 to start, A= 65, B = 80.
[soundlevel-0240.zip](https://github.com/lancaster-university/codal-microbit-v2/files/10711081/soundlevel-0240.zip)
onLoud seems to trigger maybe once after a level change.

Built with 0.2.43, [test-soundlevel-v2-0243.zip](https://github.com/lancaster-university/codal-microbit-v2/files/10714331/test-soundlevel-v2-0243.zip) seems to trigger the on loud events as expected.
The range of levels I see has changed from [52,87] in 0.2.40 to [33,103] in 0.2.43.

Testing with latest master depends on https://github.com/lancaster-university/codal-microbit-v2/issues/269.

**Comment by microbit-carlos** [comment]
@martinwork could you also test the Makecode test programme in this test deployment with CODAL 0.2.49?
https://makecode.microbit.org/app/d4edbad2afea7659ac6cb7bc231bf71183ee861a-980f0ccdaf

Thanks!

**Comment by martinwork** [comment]
@microbit-carlos The original MakeCode test seems OK.
- low CODAL levels are clipped to MakeCode level zero
- there is a quiet event when RESET is pressed

But this example is strange https://makecode.microbit.org/_9m42M89hJMXb
Including loud and quiet handlers seems to cause sound level readings to be stuck a zero. After deleting the handlers, non-zero levels are back.
In MakeCode v5, this works as expected, flashing LEDs on the left for loud & quiet events, and flickering the LED on the right for any level above 0.
Would you like a new issue for this?

**Comment by microbit-carlos** [comment]
Yes, could you open a new issue with a C++ demo to replicate the issue? Thanks Martin!

Is this issue then good to be closed?

**Comment by microbit-carlos** [comment]
Issue https://github.com/lancaster-university/codal-microbit-v2/issues/283 has been raised, so I'll close this one.
