### ISSUE TITLE
target_panic(DEVICE_NOT_IMPLEMENTED) is not valid

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#278]
DEVICE_NOT_IMPLEMENTED is -1013, which is not suitable for a panic
https://github.com/lancaster-university/codal-core/blob/master/inc/core/ErrorNo.h#L68
https://github.com/lancaster-university/codal-core/blob/75b92a9ef3a206cdc63f65576c03e2aa72b4a45b/inc/driver-models/LowLevelTimer.h#L74

**Comment by JohnVidler** [comment]
Fixed in https://github.com/lancaster-university/codal-core/commit/e6e01f1f64c7fb6d530d28f8cbb53ec0f27bbd82
