### ISSUE TITLE
Should `StreamRecording.play()` be blocking and add a non-blocking `playAsync()`?

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#317]
`MemorySource` and `SoundExpressions` have already set up that pattern, does it make sense to do the same for `StreamRecording`?

The workaround in MakeCode, MicroPython and the OOB would be to just wait while `StreamRecording.isPlaying()` returns true, so not a big deal at all.

**Comment by JohnVidler** [comment]
Play renamed to playAsync(), and a new 'play' added for blocking playback, similar added for record

**Comment by JohnVidler** [comment]
This should now be fixed in v0.2.54, but pxt is having issues integrating the changes, so keeping this issue open just in case...
