### ISSUE TITLE
Halving the recording sampling rate doesn't seem to double the max length

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#322]
Both these hex files record sound until the memory is full, one configured at 5.5K and the other at 11K, but the both only record less than 5 seconds of audio.
[5500.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/11500791/5500.hex.zip)
[11000.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/11500792/11000.hex.zip)

It's possible I'm not configuring the pipeline correctly, is this code correct?
```cpp
#include "MicroBit.h"
#include "StreamRecording.h"

MicroBit uBit;

static const int SAMPLE_RATE = 11000;

static void onButtonLogo(MicroBitEvent) {
    static SplitterChannel *splitterChannel = uBit.audio.splitter->createChannel();
    splitterChannel->requestSampleRate(SAMPLE_RATE);
    static StreamRecording *recording = new StreamRecording(*splitterChannel);
    static MixerChannel *channel = uBit.audio.mixer.addChannel(*recording, SAMPLE_RATE);

    MicroBitAudio::requestActivation();
    channel->setVolume(75.0);
    uBit.audio.mixer.setVolume(1023);

    uBit.display.clear();
    uBit.audio.levelSPL->setUnit(LEVEL_DETECTOR_SPL_8BIT);

    recording->record();
    bool showR = true;
    while (uBit.logo.isPressed() && recording->isRecording()) {
        if (showR)
            uBit.display.print("R");
        else
            uBit.display.clear();
        uBit.sleep(150);
    }
    recording->stop();

    recording->play();
    while (recording->isPlaying()) {
        uBit.sleep(20);
    }
    recording->erase();
}

int main() {
    uBit.init();

    uBit.messageBus.listen(MICROBIT_ID_LOGO, MICROBIT_BUTTON_EVT_DOWN, onButtonLogo);

    while (true) {
        uBit.sleep(100);
    }
}
```

**Comment by JohnVidler** [comment]
The code here is correct, but the current implementation of `StreamRecording` simply collects upto `REC_MAX_BUFFERS` in an array, rather than dynamically tracking blocks until it hits a specific memory limit.

I'll be updating this shortly so that rather than a buffer limit, we use a soft memory limit.

**Comment by JohnVidler** [comment]
As a note to myself:

- [ ] `REC_MAX_BUFFERS` should be replaced with a suitable `CODAL_*` config var
- [ ] Add event for reaching the soft limit
- [ ] Add default'd constructor arg to allow users to specify a custom limit per instance up to CODAL_* .. max

**Comment by microbit-carlos** [comment]
Ah, thanks John! I mistakenly thought it allocated buffers until there wasn't more memory available.

**Comment by microbit-carlos** [comment]
I've tested this with the latest commit 02a85fa86a00ac204cbd2a4caacd5a964e1cf26e, and reducing the sampling rate in the example doesn't increase the recording time. Going from 11_000 to 1_100 decreases the sound quality but still has around 5 seconds of audio.

**Comment by microbit-carlos** [comment]
I wasn't using `"dev": true` in the `codal.json` file, so I wasn't using the latest commits from codal-core.
With the latest I can confirm this now works 🎉
