### ISSUE TITLE
Delay from using the microphone and the LED turning off

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#325]

**Comment by microbit-carlos** [comment]
`CODAL_DATASTREAM_HIGH_WATER_MARK` is already at a low value of `4`, based on @JohnVidler's recommendation we shouldn't reduce any further.
We can try reducing the `CODAL_STREAM_IDLE_TIMEOUT_MS` value, the OOB is currently using `75` and seems to do okay, but I haven't tried it with other CODAL programmes.

**Comment by JohnVidler** [comment]
Adjusted `CODAL_STREAM_IDLE_TIMEOUT_MS` down to 75ms for the next tag, as this seems to be fine from testing locally.
