### ISSUE TITLE
MY_DATA on iPad - mime type of Download CSV data is "text/plain"

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#327]
Could the mime type of MY_DATA Download CSV be "text/csv"?
I want to convert the mime type to a file extension, needed because I haven't managed to find the file name associated with the blob.

**Comment by microbit-carlos** [comment]
Sounds very reasonable, could you raise a PR with the change? Thanks!

**Comment by martinwork** [comment]
@microbit-carlos Will changing this do it?
https://github.com/lancaster-university/codal-microbit-v2/blob/e4caa98354432f83c65a2b3b23829677e570211d/resources/logfs/header.html#LL48C65-L48C75

Does that get replaced by the online version?

**Comment by martinwork** [comment]
PR https://github.com/lancaster-university/codal-microbit-v2/pull/339

**Comment by microbit-carlos** [comment]
PR https://github.com/lancaster-university/codal-microbit-v2/pull/339 merged 🎉
