### ISSUE TITLE
HOW WORKS ubit.display.print?

### ISSUE THREAD

**Issue by crisgplj** [lancaster-university/codal-microbit-v2#347]
I want create a function withn nrfsdk to emulated.

Only i can write rows and columns but its difficult.

Thanks!

**Comment by microbit-carlos** [comment]
Hi @crisgplj

You can find the source code for that here: https://github.com/lancaster-university/codal-core/blob/master/source/drivers/AnimatedDisplay.cpp

Hope that helps!

**Comment by crisgplj** [comment]
thanks!

**Comment by microbit-carlos** [comment]
No problem! I'll close this as resolved, but feel free to reopen if you have any questions or find any issues 👍
