### ISSUE TITLE
Recording & Playback tests

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#352]
We currently don't have any tests in the `microbit-v2-samples` repository for the recording and playback.

**Comment by microbit-carlos** [comment]
@JohnVidler I think you mentioned tests have been added to the samples repo? Is that correct?
Are there sufficient tests to close this issue?

**Comment by JohnVidler** [comment]
There's a basic test suite over at https://github.com/lancaster-university/microbit-v2-samples/blob/master/source/samples/StreamAPITest.cpp for this now, so closing this as complete.
