### ISSUE TITLE
Recording & playback: High pitch frequency after the first recording

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#379]
Can be tested with with this MakeCode programme:

-  https://makecode.microbit.org/_VziHPeD7a3XJ
<img width="365" alt="image" src="https://github.com/lancaster-university/codal-microbit-v2/assets/29712657/3b052ee7-fe38-4936-9590-55d17e7e9914">

```ts
input.onButtonPressed(Button.A, function () {
    record.setSampleRate(11000)
    basic.showString("?")
    record.startRecording(record.BlockingState.Blocking)
    basic.showLeds(`
        . # . . .
        . # # . .
        . # # # .
        . # # . .
        . # . . .
        `)
    record.setSampleRate(18000)
    record.playAudio(record.BlockingState.Blocking)
    basic.clearScreen()
})
```

Tested with MakeCode live running CODAL v0.2.57
makecode.microbit.org version:  [6.0.18](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.18)
Microsoft MakeCode version:  [9.0.12](https://github.com/Microsoft/pxt/releases/tag/v9.0.12)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.57](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.57)

And with a test deployment of MakeCode using CODAL v0.2.60-master.1:
makecode.microbit.org version:  [6.1.5](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.1.5)
Microsoft MakeCode version:  [9.1.11](https://github.com/Microsoft/pxt/releases/tag/v9.1.11)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.60-master.1](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.60-master.1)

Hex to reproduce: [microbit-Parrot-0260-master1 (1).hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/12675716/microbit-Parrot-0260-master1.1.hex.zip)

**Comment by microbit-carlos** [comment]
I can still replicate this issue with current MakeCode Live:

makecode.microbit.org version:  [6.0.19](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.19)
Microsoft MakeCode version:  [9.0.12](https://github.com/Microsoft/pxt/releases/tag/v9.0.12)
microbit runtime version:  [v2.2.0-rc6](https://github.com/lancaster-university/microbit/releases/tag/v2.2.0-rc6)
codal-microbit-v2 runtime version:  [v0.2.61](https://github.com/lancaster-university/codal-microbit-v2/releases/tag/v0.2.61)

**Comment by microbit-carlos** [comment]
Still replicable with MakeCode using CODAL v0.2.63.

**Comment by JohnVidler** [comment]
I've re-tested this on v0.2.66, and it now seems to be gone.

Can you confirm this please @microbit-carlos ?

**Comment by microbit-carlos** [comment]
I can confirm the high frequency noise is present in MakeCode live with CODAL v0.2.63, and fixed in the test deployment version of MakeCode with CODAL v0.2.66.
