### ISSUE TITLE
Data log "full" marker is not being written to interface storage

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#406]
Running this programme on tag v0.2.63, which writes to the data log one byte at a time until the log is full:
```cpp
#include "MicroBit.h"

MicroBit uBit;

int main() {
    uBit.init();

    uBit.display.print("?");

    while (true) {
        uBit.log.logString("X");
        uBit.sleep(1);

        if (uBit.log.isFull()) {
            uBit.display.print("D");
            uBit.sleep(100);
        }
    }
}
```
[MICROBIT.hex.zip](https://github.com/lancaster-university/codal-microbit-v2/files/14284689/MICROBIT.hex.zip)

We should expect the last 4 bytes, which are reserved for this marker, to contain `FULL`:
https://github.com/lancaster-university/codal-microbit-v2/blob/d54ce9b784ef1bba22c075b281bb877abf53ea18/source/MicroBitLog.cpp#L258
https://github.com/lancaster-university/codal-microbit-v2/blob/d54ce9b784ef1bba22c075b281bb877abf53ea18/source/MicroBitLog.cpp#L738-L742

However, the last 4 bytes are left untouched: [MY_DATA.HTM.txt](https://github.com/lancaster-university/codal-microbit-v2/files/14284685/MY_DATA.HTM.txt)

<img width="370" alt="image" src="https://github.com/lancaster-university/codal-microbit-v2/assets/29712657/070c4a64-4a45-4640-a52a-6b43d855c0b8">

**Comment by jaustin** [comment]
This is odd - do you know whether the byte-by-byte case ever wrote 'log full'? Does it still work if logging longer lengths? From MakeCode?

**Comment by microbit-carlos** [comment]
It must have worked at some point, as I believe that's how the "log full" message is meant to be displayed:
- https://github.com/lancaster-university/codal-microbit-v2/issues/140

I haven't tried it in MakeCode yet.

**Comment by martinwork** [comment]
It does get to this point (even with a long string to fill memory more quickly)
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/MicroBitLog.cpp#L740

But I think the last byte before flash.getFlashEnd() is blocked by the equals in this test
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/FSCache.cpp#L119
and
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/FSCache.cpp#L87

With ">=" changed to ">" in the FSCache test, the I2C transaction seems OK, but it still seems to be zeros in the file.
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/MicroBitUSBFlashManager.cpp#L369
```
FSCache::write address 0x1EFFD length 3 getFlashEnd 0x1F000
FUL
MicroBitUSBFlashManager::write 0x1EFFC 4
request 0xB 0x1 0xEF 0xFC 0x0 0x0 0x0 0x4 0xFF 0x46 0x55 0x4C
response 0xB 0x1 0xEF 0xFC 0x0  0x0 0x0 0x4 0xFF
```

**Comment by martinwork** [comment]
Ah! I forgot the USB must be reconnected to see the latest data... FUL is there!

**Comment by martinwork** [comment]
FUL is saved when the FSCache::write test is changed to ">", 
![image](https://github.com/user-attachments/assets/9a0548c9-a9ed-43f1-8516-d3d377760b90)
but it doesn't always make LOG FULL appear.
![image](https://github.com/user-attachments/assets/a7286c5e-baae-41a0-91be-a97bb5b151e9)
[MY_DATA.HTM.txt](https://github.com/user-attachments/files/16382978/MY_DATA.HTM.txt)

**Comment by martinwork** [comment]
Will do!
