### ISSUE TITLE
Investigate why CODAL v0.2.65 reduces the recording length in MakeCode

### ISSUE THREAD

**Issue by microbit-carlos** [lancaster-university/codal-microbit-v2#440]
Reported in:
- https://github.com/microsoft/pxt-microbit/issues/5796

MakeCode [v6.0.28](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.28) with CODAL v0.2.63 records for 4.5 seconds:
- https://makecode.microbit.org/app/ebe1449535c86e6a8cb04ae0c8c4b47882de0c5f-1bead1a6cb 

MakeCode [v6.0.28](https://github.com/Microsoft/pxt-microbit/releases/tag/v6.0.28) with CODAL v0.2.65 only for ~1.2 seconds:
- https://makecode.microbit.org/app/134e1a256376e01e23911f3bdb4e7da337927e6d-abdab27977

**Comment by martinwork** [comment]
@microbit-carlos The default sample rate was changed from 11000 to 44100.
https://github.com/lancaster-university/codal-microbit-v2/commit/2e664e6294749c1444c002d2276674c3210ba0b8

Recording time is restored by adding a `set sample rate` block.

**Comment by microbit-carlos** [comment]
Yes, thanks Martin!
It was changed from a magic number to a config option in https://github.com/lancaster-university/codal-microbit-v2/commit/d54ce9b784ef1bba22c075b281bb877abf53ea18, so set to 11K, but that also affected the mixer channel default, so maybe that's why it was pushed up to top value 44.1K.

MakeCode was depending on the default value, so the recording extension needs to set splitter channel sample rate to the default used in the extension.

**Comment by microbit-carlos** [comment]
PR raised in MakeCode:
- https://github.com/microsoft/pxt-microbit/pull/5805

**Comment by microbit-carlos** [comment]
Fix merged in MakeCode, so we can close this as completed.
