### ISSUE TITLE
Feature Request: BLE Profiles

### ISSUE THREAD

**Issue by microbit-sam** [lancaster-university/codal-microbit-v2#56]
Add support for common BLE profiles e.g. Heart Rate, HID over GATT, Battery Information
https://en.wikipedia.org/wiki/Bluetooth_Low_Energy#Applications

(currently possible using espruino)

**Comment by bsiever** [comment]
For what it's worth, this is related to https://github.com/lancaster-university/codal-microbit-v2/issues/162 and https://github.com/lancaster-university/codal-microbit-v2/issues/160 .   

I've gotten HID to work by doing some hacks around these issues.  Hacks are shown in https://github.com/bsiever/microbit-pxt-blehid.   

One of my early prototypes included an example Battery Service and Scan Parameter Service: https://github.com/bsiever/microbit-pxt-blehid/tree/AllServices. (BatteryService.[cpp,h] and ScanParameterService.[cpp,h]). 

Heart Rate Service seems like a straight forward extension of things I'm going in HID.   I think both HID and Heart Rate benefit from the two issues linked above.
