### ISSUE TITLE
UIPM: RECEIVED UNKNWON FRAME?

### ISSUE THREAD

**Issue by martinwork** [lancaster-university/codal-microbit-v2#57]
The power manager sends DMESG("UIPM: RECEIVED UNKNWON FRAME") during the BLE DFU reboot.

This also occurs after uBit.accelerometer.setPeriod(0), sets the LSM303 ODR to 0x80 = Low-power mode (1.620 kHz).

**Comment by finneyj** [comment]
Hi @martinwork 

This is harmless - just a debug message indicating that the KL27 firmware was probed for a message as a result of an interrupt, but no data was available. It does happen occasionally as the IRQ line is shared with the motion sensor.
