### ISSUE TITLE
Touch pin triggered when mic casing is touched

### ISSUE THREAD

**Issue by microbit-mark** [lancaster-university/codal-microbit-v2#58]
Using a simple touch program in MakeCode:

https://makecode.microbit.org/_C0xg4ievw4C0

1. Download program
2. Touch logo. See face on display. Face clears
4. Touch finger to mic casing on back of board. Logo touch is triggered

It isn't specifically the microphone casing that triggers the touch, but making a connection with components in that area.

https://user-images.githubusercontent.com/31242877/116071847-477af100-a686-11eb-9857-e5f381d9fddc.mp4

We raised this initially in 
https://github.com/microbit-foundation/codal-microbit/issues/130 and the calibration was fixed for touching around the nRF52

**Comment by finneyj** [comment]
Is the reset step important @microbit-mark ?

**Comment by finneyj** [comment]
I can't repro on my v with this, but I can trigger it is I wiggle enough around the NRF52 just next to the microphone casing.

```
#include "MicroBit.h"

MicroBit uBit;

void onTouchFace2(MicroBitEvent e)
{
    uBit.display.print("J");
}

int main()
{
    uBit.init();
    uBit.messageBus.listen(MICROBIT_ID_FACE, MICROBIT_BUTTON_EVT_CLICK, onTouchFace2);

    release_fiber();
}
```

**Comment by finneyj** [comment]
We can of course adjust the default sensitivity, but I think we need a process to decide what that should be... or we'll just keep chasing our tails around... It is also important to test on both battery and USB power - the resistive component associated with a well grounded USB power supply will increase sensitivity substantially,

There is already an API to adjust the sensitivity:
https://github.com/lancaster-university/codal-core/blob/master/source/drivers/TouchButton.cpp#L91

The current default is set to 3500 (higher values are less sensitive) is defined here: 
https://github.com/lancaster-university/codal-microbit-v2/blob/master/target.json#L42

**Comment by microbit-mark** [comment]
> Is the reset step important @microbit-mark ?

No. This is just to reset the MakeCode program.

> There is already an API to adjust the sensitivity:
https://github.com/lancaster-university/codal-core/blob/master/source/drivers/TouchButton.cpp#L91

Perhaps if there is an API we should look to expose this as an advanced feature in the editors. @pelikhan @abchatra for ref.

**Comment by microbit-mark** [comment]
> micro:bit support ticket #44922

This has also been noted in the wild by a user asking if it is a bug. I've tested this again on USB and battery and updated the ticket to note that it appears to be the connection around the casing not the mic casing itself that cause the issue, so I expect this is the same as https://github.com/microbit-foundation/codal-microbit/issues/130

**Comment by microbit-mark** [comment]
@microbit-carlos Not often. I had another issue recently where the logo appeared to be triggered on start, without touching it so waiting to see if it is similar. Perhaps we should try it with a bunch of people to see if it's easily triggered.

**Comment by microbit-carlos** [comment]
We haven't really got more reports about this since the calibration/sensitivity was changed, so we can close this as completed.

**Comment by jaustin** [comment]
Reminded me to file https://github.com/microsoft/pxt-microbit/issues/5653
