### ISSUE TITLE
Ability to stop a sound expression

### ISSUE THREAD

**Issue by pelikhan** [lancaster-university/codal-microbit-v2#6]
We need to be able to button-smash a button and play the latest sound expression.

**Comment by jaustin** [comment]
This is nice for ‘button bashing’ and avoids queues. It’s also the behaviour I’d expect if we were playing back a sample so you can make a sampler that plays back the ‘sample’ ’s s s s sample sam sam sample’ if you press the button at the right time.

**Comment by finneyj** [comment]
But you might also want the queuing behaviour... The ability to back-to-back sounds also has applications.

Would it make sense to follow the design pattern we have for other long running tasks, like scrolling/animating the display:
https://github.com/lancaster-university/codal-core/blob/master/source/drivers/AnimatedDisplay.cpp#L252

Here we have an explicit abort... the cancels any active animation and moves onto the next one. 

I'm not sure I agree this behaviour is what you'd expect for playing back a sample. it' snot like you say 

print ("Jonny");
print ("Jonny");
print ("Jonny");

and expect J-J-Jonny... 

:)

**Comment by pelikhan** [comment]
Having a block to abort any sound works too.

________________________________

**Comment by finneyj** [comment]
Support for this added as of v0.2.15...
https://github.com/lancaster-university/codal-microbit-v2/blob/master/source/SoundExpressions.cpp#L103
