### ISSUE TITLE
Feature request: Sound recording API 

### ISSUE THREAD

**Issue by microbit-mark** [lancaster-university/codal-microbit-v2#70]
The micro:bit microphone can detect changes in sound levels and there have been various discussions and references to how sound recording could be implemented eg https://github.com/microsoft/pxt-microbit/issues/3423#issuecomment-709333670 and prior to V2 release in https://github.com/microbit-foundation/api-prototypes (private repo).

There are also privacy concerns around recording sound that need to be factored in.

This ticket is a public reference point to discuss the implementation of sound recording

**Comment by microbit-carlos** [comment]
This has been released with v0.2.37 🎉
