### ISSUE TITLE
Expose isSilent() method in audio mixer

### ISSUE THREAD

**Issue by finneyj** [lancaster-university/codal-microbit-v2#90]
As discussed in:
https://github.com/microbit-foundation/micropython-microbit-v2/issues/50

**Comment by microbit-carlos** [comment]
@martinwork is this something you can look into implementing?

**Comment by martinwork** [comment]
@finneyj  https://github.com/lancaster-university/codal-microbit-v2/pull/91

**Comment by martinwork** [comment]
@finneyj PR #91 has been merged. I would close if I could : )

**Comment by finneyj** [comment]
:) Nice piece of diplomacy sir. Github invite sent.
